"""
schemas.py

This module defines the data structures (Pydantic models) used for 
API request and response validation. It ensures a strict contract between 
the client and the AI agent.
"""

from pydantic import BaseModel, Field
from typing import List



class AgentQueryRequest(BaseModel):
    query: str = Field(
        min_length=1,
        description="User question to be processed by the AI agent"
    )


class AgentQueryResponse(BaseModel):
    answer: str = Field(
        description="Final answer generated by the AI agent"
    )
    documents_used: List[str] = Field(
        default_factory=list,
        description="List of document IDs or titles used for answering"
    )
    agent_decision: str = Field(
        description="Decision taken by the agent to produce the answer"
    )
